[project]
name = "django-youtube-clone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "django>=6.0.1",
    "imagekitio>=5.1.0",
    "python-dotenv>=1.2.1",
    "python-json-logger>=2.0.7",
]
